// Generated by CoffeeScript 1.3.3

module.exports = function(app) {
  var add_type, fs, thread_type;
  add_type = require('./rest').add_type;
  fs = require('fs');
  thread_type = add_type(app, 'thread', {});
  app.get('/add_video', function(req, res) {
    return res.render('add_video');
  });
  return app.post('/add_video', function(req, res) {
    return fs.readFile(req.files.video.path, function(err, data) {
      return res.send(data);
    });
  });
};
